#
# Copyright (c) 2018, Tano Systems. All Rights Reserved.
# Anton Kikin <a.kikin@tano-systems.com>
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for LLDP daemon
LUCI_DEPENDS:=+lldpd

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
