#!/bin/sh /etc/rc.common

START=90
USE_PROCD=1

start_service() {
		stop_service
		procd_open_instance
		procd_set_param command minieap
		procd_set_param file /etc/minieap.conf
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_close_instance
		echo "MiniEAP STARTED"
}

stop_service() {
		echo "MiniEAP STOPPED"
}

reload_service() {
	restart
}
