#PO = wifidog
#by walkingsky

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI wifidog config
LUCI_DEPENDS:=+wifidog
LUCI_PKGARCH:=all
PKG_NAME:=luci-app-wifidog

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
#
#
#
#

