include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for CloudDrive2
LUCI_DEPENDS:=+clouddrive2
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
