#!/bin/sh /etc/rc.common

START=35
STOP=85
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/accel-pppd -d -c /etc/accel-ppp/accel-ppp.conf -p /var/run/accel-pppd.pid
	procd_set_param respawn
	procd_close_instance
}

stop_service(){
	killall -3 accel-pppd >/dev/null 2>&1
	rm -rf /var/run/accel-pppd.pid
}

reload_service() {
	procd_send_signal accel-ppp
}

service_triggers()
{
	procd_add_reload_trigger accel-ppp
}
