include $(TOPDIR)/rules.mk

LUCI_TITLE:=MentoHUST 802.1X Client for LuCI
LUCI_DEPENDS:=+mentohust
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-mentohust

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
