#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

PROG=/usr/bin/hickory-dns
CONF=/etc/hickory-dns/forwarder.toml

start_service() {
    procd_open_instance hickory-dns
    procd_set_param command $PROG -c $CONF -p 5335 -q
    procd_set_param user root
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
    procd_close_instance hickory-dns
}
