# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for iStoreEnhance
LUCI_DEPENDS:=+istoreenhance
LUCI_PKGARCH:=all
# PKG_RELEASE MUST be empty for luci.mk

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

