#!/bin/sh

general=$(uci -q get kcptun.@general[-1])

if [ -z "$general" ]; then
	uci -q add kcptun general
fi

if [ ."$general" != ."general" ]; then
	uci -q batch <<-EOF >/dev/null
		rename kcptun.@general[-1]="general"
		set kcptun.general.server=""
		commit kcptun
	EOF
fi

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
