#!/bin/sh /etc/rc.common
# Copyright (c) 2011-2015 OpenWrt.org

START=95
mproxy_port=8080

start() {
	service_start /usr/bin/mproxy -T -l $mproxy_port -h 127.0.0.1:1194 -d
	#iptables -A INPUT -p tcp --dport $mproxy_port -j ACCEPT
	echo "mproxy has started."
}

stop() {
	service_stop /usr/bin/mproxy
	#iptables -D INPUT -p tcp --dport $mproxy_port -j ACCEPT
	echo "mproxy has stopped."
}

restart() {
	stop
	sleep 1
	start
}
