include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for mnh
LUCI_DEPENDS:=+luci-compat +mnh
LUCI_PKGARCH:=all

PKG_LICENSE:=BSD-3-Clause

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
