name: Clean jsDelivr Cache

on: 
  # push
  # https://github.com/qinxs/cdn-assets
  push:
    branches: 
      - master
      - dev
      - core
      - package
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  jsDelivr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # https://github.com/marketplace/actions/git-changesets
    - id: changed_files
      name: git-changesets
      uses: collin-miller/git-changesets@v0.0.4
      with:
          # Default format is 'csv'. Other valid options are 'space-delimited' and 'json'.
          format: space-delimited

    - name: Clean jsDelivr Cache
      run: |
          for i in ${{ steps.changed_files.outputs.added_modified }}; do
             # echo ${{ steps.changed_files.outputs.all }}
             curl -sL --retry 3 https://purge.jsdelivr.net/gh/vernesong/OpenClash@${{ github.ref_name }}/$i
          done
