#!/bin/sh 

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@guest-wifi[-1]
	add ucitrack guest-wifi
	set ucitrack.@guest-wifi[-1].init=guest-wifi
	commit ucitrack
EOF

rm -rf /tmp/luci-*cache
exit 0
