include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for CNS Server
LUCI_DEPENDS:=+wget
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-cns-server

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
