# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for homebox
LUCI_DEPENDS:=+homebox
LUCI_PKGARCH:=all
PKG_VERSION:=1.0.1-3
PKG_RELEASE:=

include ../luci-alias.mk

# call BuildPackage - OpenWrt buildroot signature

