mode: rule
ipv6: false
log-level: silent
allow-lan: false
tproxy-port: 7894
unified-delay: true
tcp-concurrent: true
keep-alive-interval: 15
tcp-keep-alive-interval: 15
geodata-mode: true
geodata-loader: memconservative
external-controller: 0.0.0.0:9090
external-ui: ui
dns:
  enable: true
  listen: 0.0.0.0:7874
  ipv6: false
  default-nameserver: ['1.1.1.1', '1.0.0.1', '8.8.8.8', '8.8.4.4']
  nameserver: ['https://cloudflare-dns.com/dns-query', 'https://dns.google/dns-query']
profile:
  store-selected: true
  store-fake-ip: true
  tracing: false

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
  skip-domain:
    - '+.microsoft.com'
    - '+.windows.com'

#==========================================================================#