#!/bin/sh
WAN_INTERFACE=$(echo ${INTERFACE} |grep -c wan)
qos_enable=$(uci get qos-emong.main.enable)



if [ "$WAN_INTERFACE" -ge "1" ] && [ "$ACTION" = "ifup" ] &&[ "$qos_enable" = "1" ]
then

WAN_IF=$DEVICE

/usr/bin/qos-emong start

fi


