#!/bin/sh
chmod -R +x /etc/init.d/mihomo  /etc/mihomo/* /usr/libexec/mihomo-call

rm -rf /var/luci-modulecache/; rm -f /var/luci-indexcache;
[ -x /etc/init.d/rpcd ] && /etc/init.d/rpcd reload;
exit 0
