---
proxy-providers:
  allProxy:
    type: file
    path: ./proxy_provider/allProxy.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
- name: Game
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  use:
  - allProxy
- name: BlockHost
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - REJECT
  use:
  - allProxy
- name: Umum
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  use:
  - allProxy
- name: Umum-URLTest
  type: url-test
  use:
  - allProxy
  url: 'http://www.gstatic.com/generate_204'
  interval: 10
- name: Umum-LB
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - allProxy
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: Umum-FB
  type: fallback
  lazy: true
  disable-udp: false
  use:
  - allProxy
  url: http://www.gstatic.com/generate_204
  interval: '30'
redir-port: 7892
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
unified-delay: true
external-controller: 0.0.0.0:9090
secret: telekulo
bind-address: 0.0.0.0
external-ui: ui
tcp-concurrent: true
dns:
  enable: true
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 223.5.5.5
    - udp://223.5.5.5
    - 1.1.1.1
    - 8.8.8.8
  nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - quic://dns.adguard.com:784
    - https://dns.adguard.com/dns-query
    - tls://dns.adguard.com
    - 223.5.5.5
    - udp://223.5.5.5
  proxy-server-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - quic://dns.adguard.com:784
    - https://dns.adguard.com/dns-query
    - tls://dns.adguard.com
    - 223.5.5.5
    - udp://223.5.5.5
  fake-ip-filter:
    - '*'
    - '*.lan'
  fallback-filter:
    geoip: true
    geoip-code: ID
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - +.google.com
    - +.facebook.com
    - +.fbcdn.net
    - +.ggpht.com
    - +.youtube.com
    - +.githubusercontent.com
    - +.googlevideo.com
    - +.msftconnecttest.com
    - +.msftncsi.com
    - msftconnecttest.com
    - msftncsi.com
    - +.*
ipv6: false
profile:
  store-selected: true
rules:
#- RULE-SET,YTAds,BlockHostx
- RULE-SET,Game,Game
- RULE-SET,Block,BlockHost
#- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,Umum,Umum
- MATCH,GLOBAL
rule-providers:
  Game:
    type: file
    behavior: classical
    path: ./rule_provider/game.yaml
  Block:
    type: file
    behavior: classical
    path: ./rule_provider/blockedHost2.yaml
  Umum:
    type: file
    behavior: classical
    path: ./rule_provider/umum.yaml
tproxy-port: 7895
tun:
  enable: true
  dns-hijack:
    - any:53