#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh /usr/share/cpe/rssi
    procd_set_param respawn
    procd_close_instance
}
