# Copyright (C) 2019 cc5771027
#
# This is free software, licensed under the GNU General Public License v2.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for Netkeeper
LUCI_DEPENDS:=+netkeeper
LUCI_PKGARCH:=all
PKG_VERSION:=1.2
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature