#!/bin/sh

general=$(uci -q get udp2raw.@general[-1])
if [ -z "$general" ]; then
	uci -q add udp2raw general
fi
if [ "$general"x != "general"x ]; then
	uci -q batch <<-EOF > /dev/null
		rename udp2raw.@general[-1]="general"
		set udp2raw.@general[-1].server="nil"
		commit udp2raw
	EOF
fi

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
exit 0
