#!/bin/sh
if [ ! "$(grep "sample_config" /etc/config/zerotier)" ]; then
	rm -f /etc/config/zerotier
	mv -f /etc/config/zerotier-opkg /etc/config/zerotier
fi

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@zerotier[-1]
	commit ucitrack

	delete firewall.zerotier
	commit firewall
EOF

rm -f /tmp/luci-indexcache
exit 0
