#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@autoreboot[-1]
	add ucitrack autoreboot
	set ucitrack.@autoreboot[-1].init=autoreboot
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
