#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@luci_app_control_webrestriction[-1]
	add ucitrack luci_app_control_webrestriction
	set ucitrack.@luci_app_control_webrestriction[-1].init=luci-app-control-webrestriction
	commit ucitrack
EOF

rm -rf /tmp/luci-*cache
exit 0
