#
# Copyright 2019 Telco Antennas Pty Ltd <nicholas.smith@telcoantennas.com.au>
# SPDX-License-Identifier: Apache-2.0
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for ModemManager
LUCI_DEPENDS:=+modemmanager

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
