#!/bin/sh

. /lib/functions.sh

OVERLAY="$( grep ' /overlay ' /proc/mounts )"

case "$ACTION" in
pressed)
	[ -z "$OVERLAY" ] && return 0

	return 5
;;
timeout)
	. /etc/diag.sh
	set_state failsafe
;;
released)
	button=$(uci get nettask.main.button)
	if [ "$SEEN" -lt 1 ] && [ "$button" -eq 1 ]; then
	    logger "按下按键，执行脚本"
	    pgrep -f /etc/nettask/button.sh | xargs kill -9 >/dev/null 2>&1
	    sh /etc/nettask/button.sh &
	elif [ "$SEEN" -ge 1 ] && [ "$SEEN" -le 4 ]; then
	    echo "REBOOT" > /dev/console
	    sync
	    reboot
	elif [ "$SEEN" -ge 5 ] && [ -n "$OVERLAY" ]; then
	    echo "FACTORY RESET" > /dev/console
	    jffs2reset -y && reboot &
	fi
	;;
esac

return 0
