# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-mproxy

LUCI_TITLE:=LuCI support for Mproxy
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+mproxy

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

