#!/bin/sh /etc/rc.common
START=399
EXTRA_COMMANDS="status"
EXTRA_HELP="        status Print the status of the service"

start() {
	 (/usr/bin/autokick.sh)&
}

stop() {
	s=$(ps w | grep -F 'autokick.sh' | grep -v grep)
	if [ "$s" != "" ]; then
		kill $(echo "$s" | awk '{print $1}')
	fi	
	killall autokick.sh 2>/dev/null
}

status() {
	echo ''
}