# Copyright (C) 2024-2024 nicholas9698 <nicholas9698@outlook.com>
#
# This is free software, licensed under the GNU General Public License v3.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI app for UJN China-Unicom certification
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+python3 +python3-requests +curl
PKG_DATE:=20240319

PKG_MAINTAINER:=nicholas9698 <nicholas9698@outlook.com>
PKG_LICENSE:=GPL-3.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
