

include $(TOPDIR)/rules.mk


LUCI_TITLE:=LuCI support for airconnect
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+airconnect

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

