
include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-gxu-webconnect

PKG_LICENSE:=MIT License

LUCI_TITLE:=LuCI support for GXU-WebConnect
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature