include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-pikpak-webdav
PKG_PO_VERSION:=$(PKG_VERSION)-$(PKG_RELEASE)

PKG_LICENSE:=MIT
PKG_MAINTAINER:=ykxVK8yL5L <ykxVK8yL5L@github.com>

LUCI_TITLE:=LuCI Support for pikpak-webdav
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+pikpak-webdav

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
