---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by thomas.
--- DateTime: 9/7/20 5:17 PM
---

m = Map("switchmode", translate("Gateway work mode"))
s = m:section(NamedSection, "settings", "workmode")
o = s:option(ListValue, "mode", translate("Mode"))
o:value("0", translate("Switch mode"))
o:value("1", translate("Route mode"))
o.default = "1"
o.rmempty = true

return m