include $(TOPDIR)/rules.mk

LUCI_TITLE:=Luci for School Bypass
LUCI_DEPENDS:=+rkp-ipid +ua2f
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-school

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature