#
# Copyright (C) 2021-2099 ykxVK8yL5L <https://github.com/ykxVK8yL5L>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#


include $(TOPDIR)/rules.mk

LUCI_TITLE:=luci-app-Taskschedule
LUCI_DEPENDS:=


include $(TOPDIR)/feeds/luci/luci.mk


# call BuildPackage - OpenWrt buildroot signature
