#!/bin/sh /etc/rc.common

START=99

UCISET='uci -q set'
UCIDEL='uci -q delete'
UCIADD='uci -q add_list'
LOCK=/var/lock/netwizard-boot.lock

setipv6() {
    local mode=$1
    case $mode in
        0)
            uci -q batch <<EOF
                delete network.wan6
                set dhcp.lan.ra=''
                set dhcp.lan.dhcpv6=''
                set dhcp.lan.ndp=''
                set dhcp.@dnsmasq[0].filter_aaaa="1"
                delete dhcp.lan.ra
                delete dhcp.lan.ra_default
                delete dhcp.lan.ra_slaac
                delete dhcp.lan.dhcpv6
                delete dhcp.lan.ra_flags
                delete dhcp.wan.ra
                delete dhcp.wan.ndp
                delete dhcp.wan.ra_flags
                delete dhcp.lan.dns
                add_list dhcp.wan.ra_flags='none'
                set network.lan.delegate='0'
                set network.wan.ipv6='0'
                set network.wan.delegate='0'
EOF
            ;;
        1) #pppoe
            uci -q batch <<EOF
                set dhcp.lan.ra='hybrid'
                set dhcp.lan.dhcpv6='hybrid'
                delete dhcp.@dnsmasq[0].filter_aaaa
                set dhcp.lan.ndp='relay'
                set dhcp.lan.ra_management='1'
                set dhcp.lan.ra_default='1'
                delete dhcp.lan.ra_flags
                set dhcp.wan.master='1'
                set network.wan.ipv6='auto'
                delete dhcp.lan.ra_slaac
                delete dhcp.wan.master
                delete dhcp.wan.ra_flags
                delete network.wan.delegate
                delete network.wan6.delegate
                delete network.lan.delegate
                delete network.wan6.sourcefilter
                delete network.wan6.delegate
                set network.wan6.extendprefix='1'
                set network.lan.ip6ifaceid='eui64'
                delete network.wan6.reqaddress='try'
                set network.wan6.reqprefix='auto'
                set dhcp.wan6.master='1'
                set dhcp.wan6.ra='relay'
                set dhcp.wan6.dhcpv6='relay'
                set dhcp.wan6.ndp='relay'
EOF
            ;;
        2) #siderouter
            uci -q batch <<EOF
                del dhcp.lan.ra_default
                del dhcp.lan.ra_slaac
                set dhcp.lan.ra='relay'
                set dhcp.lan.dhcpv6='relay'
                set dhcp.lan.ndp='relay'
                delete dhcp.@dnsmasq[0].filter_aaaa
                set dhcp.lan6=dhcp
                set dhcp.lan6.interface='lan6'
                set dhcp.lan6.ignore='1'
                set dhcp.lan.ra_management='1'
                del network.lan.delegate
                set network.lan.ip6assign='64'
                set network.lan6.extendprefix='1'
                set network.lan.ip6ifaceid='eui64'
                del network.lan6.delegate
                set network.lan6.reqaddress='try'
                set network.lan6.reqprefix='auto'
                set network.lan6.norelease='1'
                set dhcp.lan6.master='1'
                set dhcp.lan6.ra='relay'
                set dhcp.lan6.dhcpv6='relay'
                set dhcp.lan6.ndp='relay'
EOF
            ;;
        3)  #dhcp
            uci -q batch <<EOF
                set dhcp.lan.ra='hybrid'
                set dhcp.lan.dhcpv6='hybrid'
                set dhcp.lan.ndp='relay'
                delete dhcp.@dnsmasq[0].filter_aaaa
                set dhcp.lan.ra_management='1'
                set dhcp.lan.ra_slaac='1'
                del dhcp.lan.dns
                del dhcp.lan.ra_default
                delete dhcp.wan.ra_flags
                del dhcp.wan.ra
                del dhcp.wan.dhcpv6
                del dhcp.wan.ndp
                add_list dhcp.wan.ra_flags='none'
                set network.wan.ipv6='auto'
                set network.lan.ip6assign='64'
                set network.wan6.ifname="${wan_interface}"
                set network.wan6.reqaddress=try
                set network.wan6.reqprefix=auto
                delete dhcp.wan.master
                delete dhcp.wan.ra_flags
                delete network.wan.delegate
                delete network.wan6.delegate
                delete network.lan.delegate
                delete network.wan6.sourcefilter
                delete network.wan6.delegate
                set network.wan6.extendprefix='1'
                set network.lan.ip6ifaceid='eui64'
                set dhcp.wan6.master='1'
                set dhcp.wan6.ra='relay'
                set dhcp.wan6.dhcpv6='relay'
                set dhcp.wan6.ndp='relay'
EOF
            ;;
    esac
}

setsynflood(){
    if [ "x$synflood" = "x1" ] ;then
        $UCISET firewall.@defaults[0].syn_flood='1'
        $UCISET firewall.@defaults[0].synflood_protect='1'
    else
        $UCIDEL firewall.@defaults[0].syn_flood
        $UCIDEL firewall.@defaults[0].synflood_protect
    fi
}

setforwarding(){
    uci -q delete firewall.@forwarding[0] >/dev/null 2>&1
    uci add firewall forwarding > "/dev/null" 2>&1 
    $UCISET firewall.@forwarding[-1].src='lan'
    $UCISET firewall.@forwarding[-1].dest='wan'
}

sethttps() {
    local cfg=$1
    config_get https "$cfg" https '0'
    
    if [ -n "$(command -v nginx)" ]; then
        if [ -z "`uci -q get nginx._redirect2ssl`" ]; then
            $UCISET nginx._redirect2ssl=server
            $UCISET nginx._redirect2ssl.server_name='_redirect2ssl'
            $UCISET nginx._redirect2ssl.return='302 https://$host$request_uri'
            $UCISET nginx._redirect2ssl.access_log='off; # logd openwrt'
        fi
        
        if [ "x${https}" = "x1" ] ; then
            $UCIDEL nginx.default_server.listen
            $UCIADD nginx.default_server.listen='80'
            $UCIADD nginx.default_server.listen='[::]:80'
            $UCIDEL nginx._redirect2ssl.listen
            $UCIADD nginx._redirect2ssl.listen='80 default_server'
            $UCIADD nginx._redirect2ssl.listen='[::]:80 default_server'
        else
            $UCIDEL nginx._redirect2ssl.listen
            $UCIADD nginx._redirect2ssl.listen='80'
            $UCIADD nginx._redirect2ssl.listen='[::]:80'
            $UCIDEL nginx.default_server.listen
            $UCIADD nginx.default_server.listen='80 default_server'
            $UCIADD nginx.default_server.listen='[::]:80 default_server'
        fi
        uci commit nginx
        /etc/init.d/nginx reload
    else
        /etc/init.d/uhttpd stop
        sed -i "/listen_https/d" /etc/config/uhttpd
        $UCISET uhttpd.main.redirect_https='0'
        
        if [ "x${https}" = "x1" ] ;then
            certscrt='/etc/ssl/ezopwrt.crt'
            certskey='/etc/ssl/ezopwrt.key'
            rm -f $certskey $certscrt 2>/dev/null
            
            $UCIADD uhttpd.main.listen_https='0.0.0.0:443'
            $UCIADD uhttpd.main.listen_https='[::]:443'
            $UCISET uhttpd.main.redirect_https='1' 
            
            hostname=$(uci -q get system.@system[0].hostname | awk '{print tolower($0)}' 2>/dev/null || echo 'openwrt')
            $UCISET network.lan.hostname=${hostname}
            $UCISET dhcp.@dnsmasq[0].domain="${hostname}.lan"
	         openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -keyout $certskey -out $certscrt -subj "/C=CN/CN=$hostname.lan"
            $UCISET uhttpd.main.cert="$certscrt"
            $UCISET uhttpd.main.key="$certskey"
        fi
    fi
} 

# Function to configure network settings
configure_network() {
    local cfg=$1
    local wan_proto wan_ipaddr wan_netmask wan_gateway wan_dns wan_pppoe_user wan_pppoe_pass 
    local ipv6 wifi_ssid wifi_key old_wifi_ssid old_wifi_key showhide
    local lan_ipaddr lan_netmask lan_gateway lan_dns lan_dhcp wan_interface lan_proto
    local dns_tables forwarding https synflood
    local ifname lannet netname netsum i

    config_get showhide "$cfg" showhide '0'
    config_get wan_proto "$cfg" wan_proto 'dhcp'
    config_get ipv6 "$cfg" ipv6 '0'
    config_get dnsset "$cfg" dnsset '0'
    config_get wan_interface "$cfg" wan_interface 'eth1'
    config_get lan_dhcp "$cfg" lan_dhcp '0'
    config_get synflood "$cfg" synflood '0'
    config_get lan_ipaddr "$cfg" lan_ipaddr 
    config_get lan_netmask "$cfg" lan_netmask '255.255.255.0'
    config_get lan_proto "$cfg" lan_proto 'static'
    config_get lan_gateway "$cfg" lan_gateway
    config_get lan_dns "$cfg" lan_dns
    config_get dns_tables "$cfg" dns_tables 
    config_get forwarding "$cfg" forwarding '1'
    config_get https "$cfg" https '0'
    config_get wan_ipaddr "$cfg" wan_ipaddr
    config_get wan_netmask "$cfg" wan_netmask
    config_get wan_gateway "$cfg" wan_gateway
    config_get wan_dns "$cfg" wan_dns
    config_get wan_pppoe_user "$cfg" wan_pppoe_user
    config_get wan_pppoe_pass "$cfg" wan_pppoe_pass
    config_get dhcp_proto "$cfg" dhcp_proto 'dhcp'
    
    if [ "x$showhide" = "x1" ]; then
        touch /etc/netwizard_hide
        $UCISET advancedplus.@basic[0].wizard="1"
        exit 0
    else
        rm -rf /etc/netwizard_hide 2>/dev/null
        $UCISET advancedplus.@basic[0].wizard="0"
    fi 
    
    uci commit advancedplus 
    touch $LOCK
    ifname=$(uci -q get network.lan.ifname 2>/dev/null)
    [ "x$ifname" = "x" ] && ifname="device" || ifname="ifname"
    [ -n "$wan_interface" ] || wan_interface=$(uci -q get network.wan.$ifname 2>/dev/null)
    [ -n "$wan_proto" ] || wan_proto=$(uci -q get network.wan.proto 2>/dev/null)
    [ -n "$wan_proto" ] || wan_proto="siderouter"
    $UCIDEL network.lan.gateway
    $UCIDEL network.lan.dns
    $UCIDEL firewall.@zone[0].masq
    sed -i '/^config forwarding/,/^$/d' /etc/config/firewall  # del forwarding
    # uci -q delete firewall.@forwarding[0] >/dev/null 2>&1
    [ `uci -q get network.wan 2>/dev/null` ] && $UCIDEL network.wan
    [ `uci -q get network.wan6 2>/dev/null` ] && $UCIDEL network.wan6
    [ `uci -q get network.lan6 2>/dev/null` ] && $UCIDEL network.lan6
    
    netname=$(ls /sys/class/net/ 2>/dev/null | grep -E '^(eth[0-9]+|en[op][0-9]+|usb[0-9]+|wlan[0-9]+|wl[0-9]+)')
    netsum=$(echo "$netname" | wc -l 2>/dev/null || echo 0)
    [ $netsum -gt 1 ] && {
    lannet=''
    for i in $(echo "$netname"); do
        if [ "$i" != "$wan_interface" ]; then
            lannet="${lannet} $i"
        fi
    done
    lannet=$(echo "$lannet" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
        [ "x$ifname" = "xdevice" ] && $UCISET network.@$ifname[0].ports="${lannet}" || $UCISET network.lan.$ifname="${lannet}"
    }
    uci commit network
    
    if  [ -n "$wan_interface" ]; then
        $UCISET network.wan=interface
        $UCISET network.wan6=interface
        $UCISET network.wan6.proto='dhcpv6'
        $UCISET network.wan6.delegate='1'
         $UCIDEL dhcp.wan.master
         $UCIDEL dhcp.lan.master
        
        $UCISET network.wan.metric='1'
        $UCISET network.wan.$ifname="${wan_interface}"
        $UCISET network.wan6.$ifname="@wan"
	 # firewall
         $UCIDEL firewall.@zone[1].network
        $UCISET firewall.@zone[1].masq='1'
         [ "x$ifname" = "xdevice" ] && {
                 $UCIADD firewall.@zone[1].network='wan6'
                 $UCIADD firewall.@zone[1].network='wan' 
          } || $UCISET firewall.@zone[1].network='wan wan6'
    fi
    if [ "$wan_proto" != "siderouter" ]; then
        test -n "${lan_ipaddr}"  &&  $UCISET network.lan.ipaddr="${lan_ipaddr}"  
        test -n "${lan_netmask}" &&  $UCISET network.lan.netmask="${lan_netmask}"
    fi
  
    case "${wan_proto}" in
        dhcp)
	    
	    case "${dhcp_proto}" in
                static)
                    $UCISET network.lan.proto='static'
                    if [ -n "$wan_ipaddr" ]; then
                       $UCISET network.wan.ipaddr="${wan_ipaddr}"
                    fi
                    if [ -n "$wan_netmask" ]; then
                       $UCISET network.wan.netmask="${wan_netmask}"
                    fi
                    if [ -n "$wan_gateway" ]; then
                       $UCISET network.wan.gateway="${wan_gateway}"
                    fi
                    ;;
                    
                dhcp)
                    $UCISET network.wan.proto='dhcp'
                    $UCISET network.wan.delegate='0'
                    ;;
            esac
	    [ "x$forwarding" = "x1" ] && setforwarding
            [ "x$ipv6" = "x1" ] && setipv6 3 || setipv6 0
            if [ -n "${wan_dns}" ]; then
                    $UCISET network.wan.peerdns='0'
                    uci -q add_list network.wan.dns="${wan_dns}"
	    else
                    $UCISET network.wan.peerdns='1'
            fi
            ;;

            
        pppoe)
            [ "x$forwarding" = "x1" ] && setforwarding
            [ "x$ipv6" = "x1" ] && setipv6 1 || setipv6 0
            if [ "${wan_pppoe_user} != $(uci -q get network.wan.username)" ] || [ "${wan_pppoe_pass} != $(uci -q get network.wan.password)" ] ;then
                $UCISET network.wan.proto='pppoe'
                $UCISET network.wan.username="${wan_pppoe_user}"
                $UCISET network.wan.password="${wan_pppoe_pass}"
                
                if [ -n "${wan_dns}" ]; then
                    $UCISET network.wan.peerdns='0'
                    uci -q add_list  network.wan.dns="${wan_dns}"
	    else
                    $UCISET network.wan.peerdns='1'
                fi
            fi
            ;;
            
        siderouter)
            $UCIDEL firewall.@zone[0].network
            $UCIADD firewall.@zone[0].network='lan'
            $UCIDEL dhcp.lan.ra_slaac
            case "${lan_proto}" in
                static)
                    $UCISET network.lan.proto='static'
                    if [ -n "$lan_ipaddr" ]; then
                        $UCISET network.lan.ipaddr="${lan_ipaddr}"
                    fi
                    if [ -n "$lan_netmask" ]; then
                        $UCISET network.lan.netmask="${lan_netmask}"
                    fi
                    if [ -n "$lan_gateway" ]; then
                        $UCISET network.lan.gateway="${lan_gateway}"
                        $UCISET firewall.@zone[0].masq='1'
                    fi
                    ;;
                    
                dhcp)
                    $UCISET network.lan.proto='dhcp'
                    $UCIDEL network.lan.ipaddr
                    $UCIDEL network.lan.netmask

                    ;;
            esac
            if [ -n "$lan_dns" ] ;then
		   # $UCISET network.lan.peerdns='0'
		   uci -q add_list network.lan.dns=$lan_dns
            fi
            if [ $netsum -gt 1 ]; then
                    [ "x$ifname" = "xdevice" ] && $UCISET network.@$ifname[0].ports="${lannet} ${wan_interface}" || $UCISET network.lan.$ifname="${lannet} ${wan_interface}"
            fi
            $UCISET firewall.@zone[0].masq='1'
            $UCIDEL firewall.@zone[0].network
            uci -q add_list firewall.@zone[0].network='lan'
            [ `uci show network | grep utun | wc -l` -gt 1 ] && uci add firewall.@zone[0].network='utun'
            
            [ "x$ipv6" = "x1" ] && {
                $UCISET network.lan6=interface
                $UCISET network.lan6.proto='dhcpv6'
                $UCISET network.lan6.delegate='1'
                $UCISET network.lan6.$ifname="@lan"
                setipv6 2
                uci -q add_list firewall.@zone[0].network='lan6'
            } || setipv6 0
            
            [ `uci -q get network.wan 2>/dev/null` ] && $UCIDEL network.wan
            [ `uci -q get network.wan6 2>/dev/null` ] && $UCIDEL network.wan6
            $UCIDEL firewall.@zone[1].network
            ;;
    esac

  
    setsynflood
    
    sethttps "$cfg"
    
    sed -i "/dhcp_option '6/d" /etc/config/dhcp 2>/dev/null
    sed -i "/list dns/d" /etc/config/dhcp 2>/dev/null

    if [ "x$lan_dhcp" = "x1" ]; then #no DHCP
        $UCIDEL dhcp.lan.force
        $UCISET dhcp.lan.ignore='1'
        $UCISET dhcp.lan.dynamicdhcp='0'
        $UCISET dhcp.lan.ra_slaac="1"
        $UCIDEL dhcp.@dnsmasq[0].authoritative
        $UCIDEL dhcp.@dnsmasq[0].boguspriv
        $UCIDEL dhcp.@dnsmasq[0].filterwin2k
        $UCIDEL dhcp.@dnsmasq[0].nonegcache
        $UCIDEL dhcp.lan.max_preferred_lifetime
        $UCIDEL dhcp.lan.max_valid_lifetime
    else
        $UCIDEL dhcp.lan.ignore
        $UCIDEL dhcp.lan.dynamicdhcp
        $UCISET dhcp.lan.force='1'
        $UCISET dhcp.@dnsmasq[0].authoritative='1'
	
        if [ "x$dnsset" = "x1" ]; then
            if [ "${dns_tables}" = "1" ]; then
                if [ -n "$lan_ipaddr" ]; then
                    $UCIADD dhcp.lan.dhcp_option="6,${lan_ipaddr}"
                fi
            elif [ -n "${dns_tables}" ]; then
                $UCIADD dhcp.lan.dhcp_option="6,${dns_tables}"
            fi
        fi
    fi

    config_get wifi_ssid "$cfg" wifi_ssid
    config_get wifi_key "$cfg" wifi_key
    config_get old_wifi_ssid "$cfg" old_wifi_ssid
    config_get old_wifi_key "$cfg" old_wifi_key
    
    if [ -n "${wifi_ssid}" ] && [ -n "${wifi_key}" ]; then
        idx=0
        while uci -q get wireless.@wifi-iface[$idx] >/dev/null 2>&1; do
            if [ "$(uci -q get wireless.@wifi-iface[$idx].mode 2>/dev/null)" = "ap" ]; then
                $UCISET wireless.@wifi-iface[$idx].ssid="${wifi_ssid}"
                $UCISET wireless.@wifi-iface[$idx].key="${wifi_key}"
                $UCISET wireless.@wifi-iface[$idx].encryption='psk2'
            fi
            idx=$((idx + 1))
        done
        for radio in radio0 radio1 radio2 radio3; do
            if uci -q get wireless.${radio} >/dev/null 2>&1; then
                if [ "$(uci -q get wireless.${radio}.band 2>/dev/null)" = "5g" ]; then
                    $UCISET wireless.default_${radio}.ssid="${wifi_ssid}_5G"
                else
                    $UCISET wireless.default_${radio}.ssid="${wifi_ssid}_2.4G"
                fi
                $UCISET wireless.default_${radio}.device="${radio}"
                $UCISET wireless.default_${radio}.encryption='psk2'
                $UCISET wireless.default_${radio}.key="${wifi_key}"
            fi
        done

        $UCISET netwizard.default.old_wifi_ssid="${wifi_ssid}"
        $UCISET netwizard.default.old_wifi_key="${wifi_key}"
        uci commit wireless
    fi

uci -q batch <<-EOF >/dev/null
commit advancedplus
commit uhttpd
commit system
commit netwizard
commit dhcp
commit firewall
commit network
EOF
    (sleep 2
     /etc/init.d/system reload 2>/dev/null
     /etc/init.d/rpcd reload 2>/dev/null
     /etc/init.d/uhttpd reload 2>/dev/null
     /etc/init.d/network restart 2>/dev/null
     /etc/init.d/dnsmasq reload 2>/dev/null) &
}

boot() {
    XBOOT=1
    start
    
    SSID=$(uci get wireless.@wifi-iface[0].ssid 2>/dev/null || echo "")
    KEY=$(uci get wireless.@wifi-iface[0].key 2>/dev/null || echo "")
    IPADDR=$(uci get network.lan.ipaddr 2>/dev/null || echo "192.168.10.1")
    NETMASK=$(uci get network.lan.netmask 2>/dev/null || echo "255.255.255.0")
    WAN_PROTO=$(uci get netwizard.default.wan_proto 2>/dev/null || echo "siderouter")
    LAN_PROTO=$(uci get netwizard.default.lan_proto 2>/dev/null || echo "static")
    fakemesh=$(uci get fakemesh.default.enabled 2>/dev/null || echo 0)
    
    if [ "$(uci get netwizard.default.wifi_ssid 2>/dev/null)" != "$SSID" ] || \
       [ "$(uci get netwizard.default.lan_ipaddr 2>/dev/null)" != "$IPADDR" ]; then
        
        uci set netwizard.default=netwizard >/dev/null 2>&1 || uci add netwizard netwizard
        uci set netwizard.default.wan_proto="$WAN_PROTO"
        uci set netwizard.default.lan_proto="$LAN_PROTO"
        
        if [ "x$fakemesh" != "x1" ]; then
            uci set netwizard.default.wifi_ssid="$SSID"
            uci set netwizard.default.wifi_key="$KEY"
        fi
        
        if [ "$WAN_PROTO" = "siderouter" ] && [ "$LAN_PROTO" = "static" ]; then
            uci set netwizard.default.lan_ipaddr="$IPADDR"
            uci set netwizard.default.lan_netmask="$NETMASK"
        else
            uci set netwizard.default.lan_ipaddr="$IPADDR"
            uci set netwizard.default.lan_netmask="$NETMASK"
        fi
        
        uci commit netwizard
    fi
}

start() { 
    [ -f $LOCK ] && exit 0
    [ "x$XBOOT" = "x1" ] && exit 0
    
    config_load netwizard
    config_foreach configure_network netwizard
    rm -f $LOCK 2>/dev/null
}

stop() {
    rm -f $LOCK 2>/dev/null
}