#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.timecontrol
	set firewall.timecontrol=include
	set firewall.timecontrol.type=script
	set firewall.timecontrol.path=/var/etc/timecontrol.include
	set firewall.timecontrol.reload=1
EOF

rm -rf /tmp/luci-*cache
exit 0
