#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@miaplus[-1]
	add ucitrack miaplus
	set ucitrack.@miaplus[-1].init=miaplus
	commit ucitrack
	delete firewall.miaplus
	set firewall.miaplus=include
	set firewall.miaplus.type=script
	set firewall.miaplus.path=/etc/miaplus.include
	set firewall.miaplus.reload=1
	commit firewall
EOF

rm -f /tmp/luci-indexcache
exit 0
