#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-Netkeeper-Interception
LUCI_TITLE:=LuCI for Netkeeper-Interception
LUCI_DEPENDS:=+netkeeper-interception +luci-proto-netkeeper
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
