#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.mia
	set firewall.mia=include
	set firewall.mia.type=script
	set firewall.mia.path=/etc/mia.include
	set firewall.mia.reload=1
	commit firewall
EOF

rm -f /tmp/luci-indexcache
exit 0
