---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by thomas.
--- DateTime: 10/17/20 11:39 AM
---
module("luci.controller.admin.exc_nwk", package.seeall)

function index()
    entry({ "admin", "exc_nwk" }, firstchild(), translate("Switch Settings"), 75).dependent = false
    entry({ "admin", "exc_nwk", "mode" }, cbi("exc_nwk/workmode"), translate("Mode"), 1)
end