#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@dockerd[-1]
	add ucitrack dockerd
	set ucitrack.@dockerd[-1].init=dockerd
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
/etc/init.d/dockerd restart &
exit 0
