#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@luci_app_control_weburl[-1]
	add ucitrack luci_app_control_weburl
	set ucitrack.@luci_app_control_weburl[-1].init=luci-app-control-weburl
	commit ucitrack
EOF

rm -rf /tmp/luci-*cache
exit 0
