#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@luci_app_control_timewol[-1]
	add ucitrack luci_app_control_timewol
	set ucitrack.@luci_app_control_timewol[-1].init=luci-app-control-timewol
	commit ucitrack
EOF

rm -rf /tmp/luci-*cache
exit 0
