# Copyright (C) 2020-2024 Hyy2001X <https://github.com/Hyy2001X>

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-natter2

LUCI_TITLE:=LuCI Support for Natter v2.0.0-rc2
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+natter2

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
