# Cellular status

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Cellular Network Dashboard
LUCI_DEPENDS:=+uqmi

PKG_LICENSE:=GPLv3

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
