#!/bin/sh /etc/rc.common

START=99
STOP=10

enable=$(uci get nat6-helper.@nat6-helper[0].enabled)
res=`ip -6 route | grep "default from"`
gateway=`echo $res | awk '{print $5}'`
interface=`echo $res | awk '{print $7}'`

add() {

	/usr/bin/ip -6 r add default via $gateway dev $interface
    	if !(/usr/sbin/ip6tables-save -t nat | grep -q "v6NAT"); then
        	/usr/sbin/ip6tables -t nat -A POSTROUTING -o $interface -m comment --comment "v6NAT" -j MASQUERADE
    	fi
}

start() {
	[ $enable = "0" ] && exit 0
	add > /dev/null 2>&1
}

del() {
	/usr/sbin/ip6tables -t nat -D POSTROUTING -o $interface -m comment --comment "v6NAT" -j MASQUERADE
    	/usr/bin/ip -6 r del default via $gateway dev $interface
}

stop() {
	del > /dev/null 2>&1
}
