include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-cellled
LUCI_DEPENDS:=+cellled
LUCI_TITLE:=LuCI application for showing cellular RSSI LED

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
