include $(TOPDIR)/rules.mk

PKG_MAINTAINER:=xiaobao <xiaobao@linkease.com>

LUCI_TITLE:=LuCI support for mymind
LUCI_DESCRIPTION:=all

LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

