include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-pingcontrol
LUCI_DEPENDS:=+pingcontrol



LUCI_TITLE:=LuCI network interface control

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
