#!/bin/sh /etc/rc.common

START=99
STOP=10

enable=$(uci get gxu-webconnect.@gxu-webconnect[0].enable)

start()
{
	[ $enable = "0" ] && exit 0
    /etc/gxuwc.sh Loop &
}
stop()
{
    ps -ef|grep gxuwc |grep -v grep|awk '{print $1}'| xargs kill -9 > /dev/null 2>&1
}