#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Open App Filter Module
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+appfilter

PKG_NAME:=luci-app-appfilter
PKG_VERSION:=5.0.1
PKG_RELEASE:=$(AUTORELEASE)

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
