#!/bin/sh
# Copyright 2024 Rafał Wabik (IceG) - From eko.one.pl forum
# MIT License

chmod +x /usr/bin/luci-app-at-socat 2>&1 &

rm -rf /tmp/luci-indexcache  2>&1 &
rm -rf /tmp/luci-modulecache/  2>&1 &
exit 0
