#!/usr/bin/lua
require("luci.sys")
require("luci.util")

local client_ip = luci.sys.getenv("REMOTE_ADDR")
local rt_mac = luci.util.exec("ifconfig $(uci get wiwiz.portal.lan 2>/dev/null) | grep HWaddr | awk '{print $5}' 2>/dev/null")
rt_mac = string.gsub(rt_mac, "\n", "")
local client_mac = luci.util.exec("echo \"_wiwiz_setmac('$(cat /proc/net/arp | grep 0x2 | grep '".. client_ip .." ' | awk '{print $4}')', '".. rt_mac .."');\" 2>/dev/null")
print("Content-type: application/javascript\n")
print(client_mac)