#!/bin/sh
uci -q batch <<-EOF >/dev/null
delete ucitrack.@xclient[-1]
add ucitrack xclient
set ucitrack.@xclient[-1].init=xclient
commit ucitrack
delete firewall.xclient
set firewall.xclient=include
set firewall.xclient.type=script
set firewall.xclient.path=/var/etc/xclient.include
set firewall.xclient.reload=1
commit firewall
EOF
rm -rf /etc/config/xclient-opkg /etc/xclient/*opkg >/dev/null
if [ -s "/etc/uwsgi/vassals/luci-webui.ini" ];then
	limit=$(cat /etc/uwsgi/vassals/luci-webui.ini  | grep -Eo "limit-as.*"|grep -Eo "[0-9]+")
	[ $limit -lt 5000 ] && sed -i '/limit-as/c\limit-as = 5000' /etc/uwsgi/vassals/luci-webui.ini && \
	/etc/init.d/uwsgi restart
fi
rm -rf /tmp/luci-modulecache /tmp/luci-indexcache
exit 0
