#!/bin/sh
if [ ! -f /etc/config/taskplan ]; then
    cat > /etc/config/taskplan << EOF
config global 'global'
	option customscript ' '
	option customscript2 ' '

EOF
fi
mkdir -p /etc/taskplan
touch /etc/taskplan/taskplan.log
chmod +x /usr/libexec/rpcd/luci.taskplan /etc/init.d/taskplan /etc/taskplan/taskplanrun /usr/bin/taskplanhandler
rm -rf /tmp/luci-modulecache /tmp/luci-indexcache*

exit 0
