#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@parentcontrol[-1]
	add ucitrack parentcontrol
	set ucitrack.@parentcontrol[-1].init=parentcontrol
	commit ucitrack
EOF

uci delete firewall.parentcontrol
uci set firewall.parentcontrol=include
uci set firewall.parentcontrol.type=script
uci set firewall.parentcontrol.path=/etc/parentcontrol.include
uci set firewall.parentcontrol.reload=1
uci commit firewall
rm -f /tmp/luci-indexcache
exit 0
