include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-go-aliyundrive-webdav

PKG_MAINTAINER:=jerrykuku <jerrykuku@qq.com>

LUCI_TITLE:=Luci for go-aliyundrive-webdav
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+lua +libuci-lua +go-aliyundrive-webdav

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
