#!/bin/sh

en=1 #调试开关：0关闭，1打开 ，2输出到文件
outfile="/tmp/cpe.log"	#输出文件
#日志信息
Debug() {
    tim=$(date "+%Y-%m-%d %H:%M:%S")    # 获取系统时间
    if [ "$en" -eq 1 ]; then
        echo "$tim $1"                    # 打印输出
    elif [ "$en" -eq 2 ]; then
        echo "$tim $1" >> "$outfile"      # 输出到文件
    fi
}

ATPORT()
{
	MODEMNAME="ALL"
	ATPORT=2
}