#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@pppoe-user[-1]
	add ucitrack pppoe-user
	set ucitrack.@pppoe-user[-1].init=pppoe-user
	commit ucitrack
EOF

chmod 600 /etc/config/pppoe-user
chmod 755 /etc/init.d/pppoe-user
chmod 755 /etc/ppp/ip-up /etc/ppp/ip-down
chmod 755 /etc/ppp/auth-up /etc/ppp/auth-down
chmod +x /etc/ppp/ip-up.d/* /etc/ppp/ip-down.d/*

rm -rf /tmp/luci-*cache
exit 0
