#!/bin/sh /etc/rc.common
#!/bin/sh /etc/rc.common
USE_PROCD=1
START=399

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/autokick.sh
    procd_set_param respawn
    procd_close_instance
}